schemaName: big_db

dataSources:
  ds_0:
    url: jdbc:mysql://app2:3315/temp_db
    username: dw_service
    password: dw_service_818
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
  ds_1:
    url: jdbc:mysql://app1:3306/temp_db
    username: dw_service
    password: dw_service_818
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50

shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: t_order_${id % 2}
      keyGeneratorColumnName: id

    t_user:
      actualDataNodes: ds_${0..1}.t_user_${0..1}

      keyGeneratorColumnName: id

  bindingTables:
    - t_order,t_user

  defaultDatabaseStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: ds_${id % 2}

  defaultTableStrategy:
    none:

  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator
